### ISSUE TITLE
tesis | defensa

### ISSUE THREAD

**Issue by MarceloCapozzi** [MarceloCapozzi/uade-tic18-iot-security#7]
Algunas consideraciones para el momento de la defensa y para la preparación.

- [ ] slides
  - [ ]  cortos
  - [ ] claros
  - [ ] concisos
  - [ ] poco texto
  - [ ] buena combinación de colores
- [ ] poco tiempo por slide
- [ ] animaciones (videos / demos)
- [ ] mostrar ejemplos prácticos
  - [ ]  definir objetivo de la demo
  - [ ] límites
  - [ ] análisis de resultados
- [ ] mesurar tiempo por slide
  - [ ] evitar mal uso del tiempo
  - [ ] evitar slides largos sin sentido práctico
  - [ ] evitar contenido irrelvante o con poco valor
